pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                dir("task_6"){
                    sh "pip3 install -r requirements.txt"
                    sh "python3 containers_run.py"
                } 
            }
        }
    }
}