pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                sh "pip3 install -r requirements.txt"
                sh "python3 task_3/containers_run.py" 
            }
        }
    }
}