pipeline {
    agent { docker { image 'python:3.8.3' } } 
    stages {
        stage('Stage 1') {
            steps {
                sh "python task_3/containers_run.py" 
            }
        }
    }
}